/* SPDX-License-Identifier: ((GPL-2.0 WITH Linux-syscall-note) OR BSD-2-Clause) */
/* find.h - find files as a front end to find ... -exec grep ...
   Copyright (C) 1996-2022 Paul Sheer
 */


#ifndef _FIND_H
#define _FIND_H

#define INPUTS_WITH_OPTIONS_BROWSE_LOAD		(1 << 0)
#define INPUTS_WITH_OPTIONS_BROWSE_SAVE		(1 << 6)
#define INPUTS_WITH_OPTIONS_BROWSE_DIR		(1 << 12)

#define INPUTS_WITH_OPTIONS_BROWSE_LOAD_1	(INPUTS_WITH_OPTIONS_BROWSE_LOAD << 0)
#define INPUTS_WITH_OPTIONS_BROWSE_LOAD_2	(INPUTS_WITH_OPTIONS_BROWSE_LOAD << 1)
#define INPUTS_WITH_OPTIONS_BROWSE_LOAD_3	(INPUTS_WITH_OPTIONS_BROWSE_LOAD << 2)
#define INPUTS_WITH_OPTIONS_BROWSE_LOAD_4	(INPUTS_WITH_OPTIONS_BROWSE_LOAD << 3)
#define INPUTS_WITH_OPTIONS_BROWSE_LOAD_5	(INPUTS_WITH_OPTIONS_BROWSE_LOAD << 4)
#define INPUTS_WITH_OPTIONS_BROWSE_LOAD_6	(INPUTS_WITH_OPTIONS_BROWSE_LOAD << 5)

#define INPUTS_WITH_OPTIONS_BROWSE_SAVE_1	(INPUTS_WITH_OPTIONS_BROWSE_SAVE << 0)
#define INPUTS_WITH_OPTIONS_BROWSE_SAVE_2	(INPUTS_WITH_OPTIONS_BROWSE_SAVE << 1)
#define INPUTS_WITH_OPTIONS_BROWSE_SAVE_3	(INPUTS_WITH_OPTIONS_BROWSE_SAVE << 2)
#define INPUTS_WITH_OPTIONS_BROWSE_SAVE_4	(INPUTS_WITH_OPTIONS_BROWSE_SAVE << 3)
#define INPUTS_WITH_OPTIONS_BROWSE_SAVE_5	(INPUTS_WITH_OPTIONS_BROWSE_SAVE << 4)
#define INPUTS_WITH_OPTIONS_BROWSE_SAVE_6	(INPUTS_WITH_OPTIONS_BROWSE_SAVE << 5)

#define INPUTS_WITH_OPTIONS_BROWSE_DIR_1	(INPUTS_WITH_OPTIONS_BROWSE_DIR << 0)
#define INPUTS_WITH_OPTIONS_BROWSE_DIR_2	(INPUTS_WITH_OPTIONS_BROWSE_DIR << 1)
#define INPUTS_WITH_OPTIONS_BROWSE_DIR_3	(INPUTS_WITH_OPTIONS_BROWSE_DIR << 2)
#define INPUTS_WITH_OPTIONS_BROWSE_DIR_4	(INPUTS_WITH_OPTIONS_BROWSE_DIR << 3)
#define INPUTS_WITH_OPTIONS_BROWSE_DIR_5	(INPUTS_WITH_OPTIONS_BROWSE_DIR << 4)
#define INPUTS_WITH_OPTIONS_BROWSE_DIR_6	(INPUTS_WITH_OPTIONS_BROWSE_DIR << 5)

#define INPUTS_WITH_OPTIONS_FREE_STRINGS	0x10000000

int CInputsWithOptions (Window parent, int x, int y, const char *heading,
	    char **inputs[], char *input_labels[], char *input_names[],
    char *input_tool_hint[], int *check_values[], char *check_labels[],
			char *check_tool_hints[], int options, int width);

void ctags (void);
void find_file (void);


#endif				/* ! FIND_H */

